# Generated by Django 5.2.5 on 2025-09-02 01:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pontos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='pontos_necessarios',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
