# Generated by Django 5.2.5 on 2025-09-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0002_alter_cliente_pontos_alter_recompensa_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recompensa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='Sem nome', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pontos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='pontos_necessarios',
            field=models.FloatField(),
        ),
    ]
