# Generated by Django 5.1.6 on 2025-09-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0003_recompensa_descricao_alter_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pontos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='pontos_necessarios',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pontos_usados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='fidelidade.cliente')),
                ('recompensa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fidelidade.recompensa')),
            ],
        ),
    ]
