# Generated by Django 3.2.25 on 2025-09-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0004_alter_cliente_pontos_alter_recompensa_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='data_compra',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fidelidade.cliente'),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
