services:
  - type: web
    name: sistema-fidelidade
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn frutos.wsgi
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-fidelidade-db
          property: connectionString

databases:
  - name: sistema-fidelidade-db
    plan: free
